### ISSUE TITLE
Notification deduplication for Unified Alerting

### ISSUE THREAD

**Issue by justinbwood** [aws/amazon-managed-grafana-roadmap#47]
Per the AWS Managed Grafana [docs on migrating classic alerts to Grafana alerting](https://docs.aws.amazon.com/grafana/latest/userguide/v9-alerting-use-grafana-alerts.html), multiple notifications are sent when using Grafana-managed alerts.

I would like to see Grafana's [high availability alerting](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/#enable-alerting-high-availability) enabled so that notifications are properly deduplicated, as it's a bit frustrating to receive Slack notifications in triplicate when using Unified Alerting.

Thanks!

**Comment by atze234** [comment]
I also like to see this. Really annoying with these three messages per Alert...
I filed an issue over at grafana, but it seems like theres something wrong with amazon managed grafana config.

https://github.com/grafana/grafana/issues/68652

**Comment by bradlet** [comment]
I've also been running into this issue. Opened a support ticket w/ AWS and the result was basically reflecting the doc that was [linked in this comment](https://github.com/aws/amazon-managed-grafana-roadmap/issues/47#issue-1706239195). It seems like really bad UX to spam out alerts like this... I'd be interested to hear what workarounds others have used; I'm in the process of migrating over to managing the alerts using an external alert manager, Prometheus AlertManager, instead. Would be nice to be able to provision the alert rules in Grafana though!

**Comment by atze234** [comment]
As a workaround im using a Dynamodb and a Message hash in my Lambda that parses SNS. Like here:

https://gist.github.com/atze234/60dbef2991e08aba93b875c73578cf41

Also i set this in delivery_policy so that there is enough time to write to the db.

```
    "defaultThrottlePolicy": {
      "maxReceivesPerSecond": 1
    },
```

**Comment by RphCos** [comment]
This really is needed, since the "Classic" alerting is supposedly going away soon. It makes using Slack or Pagerduty impossible when monitoring large workloads, especially since classic alerts do not allow for template variables.

**Comment by brc** [comment]
+1

**Comment by chr2che** [comment]
is there any ETA for this please?

**Comment by andrzej-mega** [comment]
Spoke to AWS team about this today. They gave an "estimate" of Q1 2024 with possibility it might be as late as Q3 2024. 
According to them it's not a high priority issue for them and there are other issues they need to work on before that happens.

My biggest issue with it is that with Grafana managed service - alerting is advertised as a service feature. 

I guess paying customers don't get a working feature until AWS deemed it worth fixing it...

**Comment by kevdonde** [comment]
We are also experiencing this issue. This is a primary feature of the service, and it is extremely disappointing that Amazon doesn't prioritize primary features of its products. We have waited for 1.5 years for Amazon to make 9.4 available in AMG so that we could use the alerting that is part of 9.4. Alerting is the only feature of 9.4 that we needed. It was/is the biggest reason to upgrade to 9.4. Now, we might further delay upgrading until as late Q3 2024 making it more than 2.5 years. 

The purpose of the above rant is to add my vote to the priority of this issue.

**Comment by webertrlz** [comment]
+1

**Comment by mortiz-77** [comment]
@VermaPriyanka do we have any updates on this and when should we expect a fix? This is really important to us!

**Comment by amorphic** [comment]
FYI @VermaPriyanka this is a showstopper for us. We considered various solutions for providing an observability service to our engineering teams and settled on Managed Grafana expecting it to Just Work. Now after a significant investment of resources to get set up and put processes in place, we've hit this bug which renders the service unfit for use. Alerting is core functionality and we cannot expect other teams to accept all of their alerts appearing 3x in Slack!

We would really appreciate a fix for this ASAP or at the very least an ETA on a fix and a standard workaround until the fix arrives.

**Comment by sukoneck** [comment]
workaround while we're waiting https://github.com/flashbots/prometheus-sns-lambda-slack

**Comment by VermaPriyanka** [comment]
Thank you all for the patience and for sharing workarounds. We understand that this is an important issue to solve and are working towards the same.

**Comment by ghost** [comment]
+1

**Comment by magnowest** [comment]
AWS released Grafana 10.4 [yesterday](https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-managed-grafana-supports-version-10-4/), and it's still an issue. 

Strangely, this was their response to the alerting in HA issue.

https://docs.aws.amazon.com/grafana/latest/userguide/v10-alerting-explore-high-availability.html

<img width="1157" alt="image" src="https://github.com/aws/amazon-managed-grafana-roadmap/assets/38874507/4ed72da5-a6b6-40be-b0f9-029c56cacd23">

**Comment by lorelei-rupp-imprivata** [comment]
> AWS released Grafana 10.4 [yesterday](https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-managed-grafana-supports-version-10-4/), and it's still an issue.
> 
> Strangely, this was their response to the alerting in HA issue.
> 
> https://docs.aws.amazon.com/grafana/latest/userguide/v10-alerting-explore-high-availability.html
> 
> <img alt="image" width="1157" src="https://private-user-images.githubusercontent.com/38874507/331196126-4ed72da5-a6b6-40be-b0f9-029c56cacd23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjE3MzksIm5iZiI6MTcxNTg2MTQzOSwicGF0aCI6Ii8zODg3NDUwNy8zMzExOTYxMjYtNGVkNzJkYTUtYTZiNi00MGJlLWIwZjktMDI5YzU2Y2FjZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEyMTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyN2MwYjJkN2Y1N2MyMTgzOWJlZGJjMGY3NGYwOGE5ODc2MWI3YjUwMzYzMzJmY2ZjOWViNWQ2MWRmMTU2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtIDC0pskBBwnVvEYx2-_z8MuduckeOLg2w7Qv-JVfU">

Yeah this is the WORST bug, I am not even sure how they can release with this issue, its been a year now, we are still stuck on the old legacy alerts because of this. That documentation almost suggests they won't fix this and its working as they designed it

**Comment by VermaPriyanka** [comment]
Thank you for voicing this concern. We are working towards a fix for the duplicate notifications issue in version 10. The description [here](https://docs.aws.amazon.com/grafana/latest/userguide/v10-alerting-explore-high-availability.html) explains the current workings of Grafana alerting, which implies rules are evaluated per HA instance. We are working towards solving this in 2 steps - focusing on solving the duplicate notifications first and to eliminate duplicate evaluations in the long term.
We understand this has been a long wait, and are working towards releasing a fix soon.

**Comment by ff-pjha** [comment]
Facing the same issue. Do you have any workarounds for slack?

**Comment by Diondk** [comment]
> Thank you for voicing this concern. We are working towards a fix for the duplicate notifications issue in version 10. The description [here](https://docs.aws.amazon.com/grafana/latest/userguide/v10-alerting-explore-high-availability.html) explains the current workings of Grafana alerting, which implies rules are evaluated per HA instance. We are working towards solving this in 2 steps - focusing on solving the duplicate notifications first and to eliminate duplicate evaluations in the long term. We understand this has been a long wait, and are working towards releasing a fix soon.

How fast can we get an fix for this, we are currently setting up alerting and its a real pain to receive all alerts 3x...

**Comment by ursuciprian** [comment]
> Thank you for voicing this concern. We are working towards a fix for the duplicate notifications issue in version 10. The description [here](https://docs.aws.amazon.com/grafana/latest/userguide/v10-alerting-explore-high-availability.html) explains the current workings of Grafana alerting, which implies rules are evaluated per HA instance. We are working towards solving this in 2 steps - focusing on solving the duplicate notifications first and to eliminate duplicate evaluations in the long term. We understand this has been a long wait, and are working towards releasing a fix soon.

any updates on this nasty ,,feature"?

**Comment by bguruprasad** [comment]
We are also facing the same issue and would really appreciate on how and when this will be fixed by aws. Do you have any fix ETA on this @VermaPriyanka ? when is the fix supposed to be released for managed grafana? I am currently on Grafana v10.4.1 and still see this issue on aws managed grafana.

**Comment by flashguerdon** [comment]
Hi @VermaPriyanka,
Any update on this issue?

**Comment by VermaPriyanka** [comment]
This is shipping soon on Managed Grafana v10.4 workspaces. 
Folks who have implemented workarounds to avoid the multiple notifications, do you see any concern as this fix is shipped - any breaking experiences or impact to your alerting flow?

**Comment by kevdonde** [comment]
I don't understand didn't 10.4 ship at the end of July?

**Comment by kevdonde** [comment]
Will you be patching 10.4 in place? Are you releasing a new minor patch to 10.4? The above statement is slightly confusing because 10.4 has already shipped.

**Comment by ingMor** [comment]
Hi @VermaPriyanka ,
we are about to implement such a workaraound (detriplication on a FIFO-SQS-SNS-basis or with Prometheus). 
If this feature is shipping soon, it might not be worth it.
So can you specify the "soon"-part of your post (and also @kevdonde 's question regarding the versioning)?
Thanks in advance,

**Comment by VermaPriyanka** [comment]
@kevdonde @ingMor  It will be in place for all 10.4 workspaces - new, existing or upgraded. If you have additional/more specific questions, you can send them via mail to [aws-grafana-feedback@amazon.com](mailto:aws-grafana-feedback@amazon.com).

**Comment by ghost** [comment]
> This is shipping soon on Managed Grafana v10.4 workspaces. Folks who have implemented workarounds to avoid the multiple notifications, do you see any concern as this fix is shipped - any breaking experiences or impact to your alerting flow?

That's great to hear. We have been avoiding creating alerts on Managed Grafana and creating on Prometheus or Cloudwatch, but our idea is to centralize all on Grafana. 

Looking forward for the release!

**Comment by Dragotic** [comment]
@VermaPriyanka when is this fix coming? Currently, Alerting is unusable due to spam of multiple alerts

**Comment by ghost** [comment]
Hi @VermaPriyanka ,

Could you provide an update on when the fix will be released? Any ETA or additional details would be appreciated.

Thanks!

**Comment by webertrlz** [comment]
I'm also standing by for the workspace fix.

**Comment by Krishnakumar-Santhanam** [comment]
Hello @VermaPriyanka, please let us know when the fix will be released. Today, we have updated AMG from `9.4` to `10.4` but the notification duplication issue persists, we tried setting different `group_interval` and `group_wait` options but no luck!

**Comment by ahsanejazzz** [comment]
Notifications are sent 3x and there is no support for Email or MS teams integration in contact points. The notification template does nothing. Thanks for "Amazon RUINED Grafana".

**Comment by Diondk** [comment]
> Notifications are sent 3x and there is no support for Email or MS teams integration in contact points. The notification template does nothing. Thanks for "Amazon RUINED Grafana".

They didn't ruined anything, you can run Grafana in an EC2 and manage it yourself you have all the options you want. Only then you are responsible for maintenance. If you don't want that you are bound to the managed Grafana. But all options you just provided are marked in the documentation that its currently not supported by AMG

To get ontopic again, hopfully this will be released soon. and are we able to deduplicate the messages. 

*edit* 

BTW you can get email notifications through sns but be aware you get 3 emails for each alert, untill this issue is resolved.

**Comment by anurag-ranjan-ibs** [comment]
+1 Real pain

**Comment by Inquisitive1a** [comment]
@VermaPriyanka : We are using Grafana-oss v11.1.3 , after upgrade from v11.0.0 we are facing this Triple firing issue ,when we can expect the solution?

**Comment by VermaPriyanka** [comment]
@Inquisitive1a This is a public roadmap for Amazon Managed Grafana. I'm unsure if you are using self-managed Grafana or Grafana Cloud.

**Comment by VermaPriyanka** [comment]
Thank you all for being patient for this update. Notifications have been sent to existing customers using Grafana alerts in Amazon Managed Grafana, about the release of an update that will prevent multiple notifications. Will share an update here, once this is available on all Amazon Managed Grafana v10.4 workspaces.

**Comment by cageyv** [comment]
Thanks for the update. We are getting these notifications in many projects. Customers will be happy.
Let's expect 1-2 weeks to get this update for everyone :) 
And check your operational contact or default contact email. If you will the exact update date inside them.

**Comment by jcquiles** [comment]
According to our AWS Health Dashboard notifications, it looks like **Sept 14th** is the date to expect for the patch to eliminate multiple alerts, you must have a **v10.4 workspace** for the update.

`Starting September 14, 2024, we will release an update that prevents multiple alert notifications sent to your alert destinations/contact points [2], from Grafana managed alert rules.`

`This update is only available for Amazon Managed Grafana version 10.4 workspaces. If you are running Grafana version 8.4 or 9.4, you must upgrade your workspace to Grafana version 10.4 to receive this update.`

**Comment by VermaPriyanka** [comment]
Thanks all for sharing here. Would like to clarify, the release starts on 9/14, so it may be a couple of days from then for you to see the effect in your workspace, depending on which region you are in.

**Comment by jcquiles** [comment]
thats good to know! thanks @VermaPriyanka

**Comment by Diondk** [comment]
I can confirm that the fix is working and i am only getting 1 notification now per server.

**Comment by anurag-ranjan-ibs** [comment]
@Diondk I am still getting 3 notification, should I have to make any changes to apply the patch ?

**Comment by Diondk** [comment]
> @Diondk I am still getting 3 notification, should I have to make any changes to apply the patch ?

no thats not needed, but please note that the release started at 9/14. Could be a couple of days before you see the effect in your workspace.

**Comment by anurag-ranjan-ibs** [comment]
@Diondk Which region are you using for your Workspace ? 
Since my workspace is in us-east-1 and there is currently no fix for it.

**Comment by Dragotic** [comment]
We are in `eu-central-1` and still no fix either.

**Comment by anurag-ranjan-ibs** [comment]
@VermaPriyanka Can you please confirm in which region is it deployed ?

**Comment by Diondk** [comment]
> @Diondk Which region are you using for your Workspace ? Since my workspace is in us-east-1 and there is currently no fix for it.

We are in EU-WEST-1, there was also no fix for me to apply myself, it was fixed when i came in the office on monday.

**Comment by Krishnakumar-Santhanam** [comment]
@VermaPriyanka We are yet to receive any fix, we are on version `10.4` and running AMG in `eu-west-1`, but alerts are still getting triggered thrice! Any ETA on when other users will receive the fix?

**Comment by VermaPriyanka** [comment]
Thank you all for your patience. We understand the anxiety at this time and would like to inform that the update has been released for all new Amazon Managed Grafana version 10 workspaces, and the release for existing version 10 workspaces is in progress. We expect the update to be worldwide by next week. No action is required from the customers for this update. 
Advance notification stating that the release starts on 9/14 was sent out to inform customers about the upcoming change in alert notifications behavior.

**Comment by VermaPriyanka** [comment]
Thank you all for your patience. Happy to share that the update to prevent multiple alert notifications sent to your contact points from Grafana managed alert rules, is now available on all Amazon Managed Grafana workspaces running Grafana version 10.4, across all AWS regions where Amazon Managed Grafana is [generally available](https://docs.aws.amazon.com/grafana/latest/userguide/what-is-Amazon-Managed-Service-Grafana.html#AMG-supported-Regions).

If you are running Grafana version 8.4 or 9.4, you must upgrade your workspace to Grafana version 10.4 to receive this update. For instructions on how to update your workspace(s), see Amazon Managed Grafana service [documentation](https://docs.aws.amazon.com/grafana/latest/userguide/AMG-workspace-version-update.html). We recommend testing the newer version in a non-production environment before updating a production workspace.

We know this has been a frustration for many of you, and we deeply appreciate your understanding and patience. Your feedback and continued support are invaluable in helping us improve, and we're committed to ensure a smoother experience going forward.

If you have any questions or continue to experience issues, please reach out to us. Alternatively, if you prefer a more private channel, feel free to reach us via email at [aws-grafana-feedback@amazon.com](mailto:aws-grafana-feedback@amazon.com).

[Public roadmap announcement](https://github.com/aws/amazon-managed-grafana-roadmap/discussions/85)

**Comment by VermaPriyanka** [comment]
Closed with https://github.com/aws/amazon-managed-grafana-roadmap/discussions/85
